version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: arnaud
      POSTGRES_PASSWORD: arnaud
      POSTGRES_DB: ats_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: